---
- name: Network Full Backup Play
  hosts: network
  gather_facts: true
  vars:
    GH_REPO: "https://github.com/rohitthakur2590/network_automation_backups"
  tasks:
    - name: Perform pre-run checks
      ansible.builtin.include_tasks:
        file: ./pre_remote_validation.yaml

    - name: Create Full Network Backup
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              user:
                name: "rohitthakur2590"
                email: "rohitthakur2590@outlook.com"
              url: "{{ GH_REPO }}"
              token: "{{ GH_TOKEN }}"
